# Generated by Django 5.0.1 on 2025-01-23 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PLAYER_WON", "Player Won"),
                            ("DEALER_WON", "Dealer Won"),
                            ("TIE", "Tie"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("player_cards", models.JSONField(default=list)),
                ("dealer_cards", models.JSONField(default=list)),
                ("deck", models.JSONField(default=list)),
                ("player_score", models.IntegerField(default=0)),
                ("dealer_score", models.IntegerField(default=0)),
                ("bet", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=1000)),
                ("games_played", models.IntegerField(default=0)),
                ("games_won", models.IntegerField(default=0)),
                ("total_won", models.IntegerField(default=0)),
                ("total_lost", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
